### ISSUE TITLE
Combine Models module not working

### ISSUE THREAD

**Issue by mauigna06** [lassoan/SlicerBoneReconstructionPlanner#22]
Steps to recreate the bug:
Load model a model in "Input model A", load another model in "Input model B", select operation "Difference (A-B)", output "Create new model node", click "Apply"

Gives the following error on the python interactor:
```Failed to compute results: No module named 'vtkSlicerCombineModelsModuleLogicPython'
Traceback (most recent call last):
  File "C:/Users/Mau/Documents/GitHub/SlicerSandbox/CombineModels/CombineModels.py", line 238, in onApplyButton
    self._parameterNode.GetParameter("Operation"))
  File "C:/Users/Mau/Documents/GitHub/SlicerSandbox/CombineModels/CombineModels.py", line 292, in process
    import vtkSlicerCombineModelsModuleLogicPython as vtkbool
ModuleNotFoundError: No module named 'vtkSlicerCombineModelsModuleLogicPython'

**Comment by lassoan** [comment]
Please try replacing line 32 in CombineModels.py to:

    logicPath = os.path.realpath(os.path.join(os.path.dirname(__file__), '../qt-loadable-modules/'+subfolder)).replace('\\','/')

**Comment by mauigna06** [comment]
I didn't install the extension from the extension manager. I just cloned the Github repository and added "CombineModels" to the additional module paths. I did this because the Sandbox extension from the extension manager wasn't updated and it didn't have the CombineModels Module

**Comment by mauigna06** [comment]
Thanks for the help. That line change didn't solve the error, it keeps appearing. (I make this comment because I think Github won't tell you that I edited the comment above to tell you I tested the line change)

**Comment by lassoan** [comment]
You either need to build the extension yourself (you need to build Slicer first) or install the pre-built extension from the extension manager.

You need the very latest (today's) Slicer Preview Release.

**Comment by lassoan** [comment]
What operating system do you use?

**Comment by mauigna06** [comment]
Windows 10 x64

**Comment by mauigna06** [comment]
> You either need to build the extension yourself (you need to build Slicer first) or install the pre-built extension from the extension manager.
> 
> You need the very latest (today's) Slicer Preview Release.

I did try to install it today from the extensions manager wiith latest preview release but I'll try again tomorrrow

**Comment by lassoan** [comment]
The Sandbox extension failed to build last night (http://slicer.cdash.org/build/2144222/configure), I've tried to reorganize the build tree, hopefully the build will succeed tonight.

**Comment by mauigna06** [comment]
I was able to install the updated Sandbox extension from the extensions manager. I tried it with 2 cylinders, with the fibula model and the mandible model and with the fibula model and one cylinder. Union operation didn't work with any. Intersection operation worked with the fibula model and the mandible model, and with the fibula model and one cylinder. Difference operation worked with the fibula model and the mandible model, and with the fibula model and one cylinder.
This observations suggest that the Combine Models module is a bit unstable but maybe good enough for using difference operation between the surgicalGuideBase and a (cylinder or sawBox)

**Comment by lassoan** [comment]
Great! Please report the bug at https://github.com/zippy84/vtkbool/issues (describe the context of the work so that the author knows that it is an important project and provide download link to the input meshes that you have trouble with, and include any VTK error message that Slicer logs when you run the processing).

In parallel, you can try to reduce, clean, and simplify the input data sets and compute normals to see if it makes any difference. You can do all these using Surface Toolbox module.

If vtkbool is not reliable then we can import all models into a segmentation and perform Boolean operations there.

**Comment by mauigna06** [comment]
I wasn't able to recreate all the bugs that I had the first time. Now I only have bugs when I try boolean operations on simple meshes like cylinders or sawBoxes. Now vtkbool appears to work well when both meshes are complex. Do you still think I should post the issue?

**Comment by mauigna06** [comment]
Hi Andras. 
I have problems getting the combineModelsLogic. Neither of these lines work (you cannot access the process function):
```combineModelsLogic = slicer.modules.combinemodels.logic()```
```combineModelsLogic = slicer.modules.combinemodels.logic```

This line works only after I open the "Combine Models" module:
```combineModelsLogic = slicer.modules.CombineModelsWidget.logic```

**Comment by lassoan** [comment]
See slide 7 of this tutorial: https://www.slicer.org/wiki/Documentation/Nightly/Training#PerkLab.27s_Slicer_bootcamp_training_materials

The correct syntax for scripted modules is: `slicer.modules.combinemodels.widgetRepresentation().self().logic`

**Comment by lassoan** [comment]
> Now vtkbool appears to work well when both meshes are complex. Do you still think I should post the issue?

Send me model pairs that do not work. I can give it a try if I can make it work with some cleaning, etc. and if I cannot figure it either then you can send the bug report.

**Comment by lassoan** [comment]
I got the example files from @mauigna06. Operations involving the cylinder models were failed because they were not triangle meshes (the base and top were polygons):

![image](https://user-images.githubusercontent.com/307929/107604077-d71f1080-6bfc-11eb-93f3-51094922033a.png)

After triangulating the surface, everything worked correctly. I used Surface Toolbox module's Decimation method (reduction set to 0.0) because I did not want to spend time with scripting, but most probably you can simply run vtkTriangleFilter.

I've also noticed that the curved surface consisted of extremely ill-shaped triangles. If you want to create such long cylinders then you can create a centerline using vtkLineSource and vtkTubeFilter.

**Comment by mauigna06** [comment]
Thanks you Andras. I'll redo the function to create cylinders
