### ISSUE TITLE
Third surgical guide created

### ISSUE THREAD

**Issue by mauigna06** [lassoan/SlicerBoneReconstructionPlanner#26]
Hi guys, here is the scene containing the latest surgical guide made with the module. Please be sure to use the branch "booleanOperationsExperiments" to open it so you can edit the parameters and do the modifications you'd like...

https://gofile.io/d/nPaSD8

![Screenshot2](https://user-images.githubusercontent.com/19158307/108536826-a8b7ca00-72bb-11eb-9ca1-a4a7703f7ae1.png)

(Before doing anything click on "Create bone models from segmentations" so the bone models are loaded to the logic )

**Comment by mauigna06** [comment]
I updated the documentation so now what is done should be understandable

**Comment by cmfsx** [comment]
I sent the guide for print

**Comment by mauigna06** [comment]
I realized that fibulaPlanes didn't intersect the miterBoxes on the previous file. Probably I changed something and forgot to update the scene. This link contains a surgicalGuide that has the fibulaPlanes on correct positions: https://gofile.io/d/MgcnE0

**Comment by cmfsx** [comment]
My friend printed the previous file. The original file although fixed did not print for some reason. I thought it was may have been due to the boolean operations of the boxes. We will try to diagnose the problem. We will try printing the parts of the guide to see where it gives trouble. 

However, I re-meshed the file and it printed well. 

![Screenshot from 2021-02-21 07-45-03](https://user-images.githubusercontent.com/57766971/108613528-f138ca00-7418-11eb-8cfb-71916f35ef26.png)

The 3D prints are not cleaned and post-processed yet. But he (who is an orthopedic surgeon)  found the guide to be sturdy and good and can be used for cutting the fibula. 

![signal-2021-02-21-024345_001](https://user-images.githubusercontent.com/57766971/108613545-0ada1180-7419-11eb-8d9a-641664db29d9.jpeg)
![signal-2021-02-21-024345_003](https://user-images.githubusercontent.com/57766971/108613550-0ca3d500-7419-11eb-935e-1538188189a7.jpeg)
![signal-2021-02-21-024413](https://user-images.githubusercontent.com/57766971/108613551-0dd50200-7419-11eb-9851-52b2ba59c882.jpeg)

This is the remeshed file.
https://mah365-my.sharepoint.com/:u:/g/personal/manjula_herath_mau_se/EQSQVUZ7KOhGpB9w9aWG6jwBunJ2tzIZX_uYmyEusjwADw?e=chN6f6

**Comment by cmfsx** [comment]
Ok we diagnose the problem with the printing and it is not related to the software.  It was due to supports. Can we make the top surface of the guide geometric/smooth flat surface as this will greatly reduce the printing time?  also then we can put the support on that side and will be easy to clean. 


![signal-2021-02-21-101657](https://user-images.githubusercontent.com/57766971/108617138-e2aeda80-7439-11eb-8368-a7a22eaf5ca0.jpeg)

still i am unable to generate the guide because the mitter boxes are not placed along the fibula line. (i tried with both 02/19 and 02/18 preview release of the 3D Slicer with sandbox installed. 

Do i need to load the volume of the Fibula as well ? 
![Screenshot from 2021-02-21 09-22-53](https://user-images.githubusercontent.com/57766971/108617199-54872400-743a-11eb-85ca-dad4dc216395.png)

**Comment by mauigna06** [comment]
You can try printing the file with the bone-touching-part facing upwards so it's smooth and you don't need to remove the supports from that side.

![108613550-0ca3d500-7419-11eb-935e-1538188189a7](https://user-images.githubusercontent.com/19158307/108625623-b2ac0b00-742a-11eb-9d6c-8d7927981ae2.jpeg)

------------

> still i am unable to generate the guide because the mitter boxes are not placed along the fibula line. (i tried with both 02/19 and 02/18 preview release of the 3D Slicer with sandbox installed. I am using the BooleanExperiment branch.

To avoid that from happening you have to click "Create bone models from segmentations" after you open the scene (only one time is needed). Then you can use the module as normal (you can click "Create miter boxes from fibula planes" and it will work well). 

I'll try to fix this bug saving the fibulaModelNode in the parametersNode instead than in a member variable. If that doesn't work, I'll try using the scene-loaded-event to aumatically load the fibulaModelNode into the parameterNode

**Comment by cmfsx** [comment]
I meant I could not generate a guide on my own from the scratch on preview releases with sandbox installed. 

Your file (both versions) works well.

**Comment by mauigna06** [comment]
We made a videocall to try to overcome the problems Manjula had. Hopefully he'll be able to design his own guides very soon

**Comment by cmfsx** [comment]
I played around today. And the results were good. For some reason, Big mitter boxes touching the bone still persisted, but i guess we will figure that out. 

![Screenshot from 2021-02-22 18-19-17](https://user-images.githubusercontent.com/57766971/108712050-3d305f80-753c-11eb-9ed9-541c248d65f6.png)

I followed @mauigna06 workflow and tried. (Mitter box problem persisted) 

But for the surgical guide base design, I skipped Mauro step of creating a new transform and align the fibula along the posterior axis. Instead, I simply used 3 fiducials to reorient/reslice the axial view of the fibula volume. Then I could simply skip all the transforming steps and hiding steps and work with scissors the same way you showed me.  Also, I used the joint smooth keeping the fibula segment visible so the contacting surfaces will keep the watertight fit while other surfaces would be smoothened.  I think the results are excellent provided I did not spend much time optimizing. If mitter boxes are placed correctly i think we are well prepared. 

Few comments, 


1. Can we use the fibula line to direct the Mitter boxes? 

2. Hide the original mandible model when transforming fibula bone pieces to mandible is done (Keep only the "Cut mandible" visible
   2.a change cut mandible to something more appropriate like "resected mandible"? 
   
3. Display the segments on the fibula also like on the mandible so the surgeon knows which piece goes where.

**Comment by mauigna06** [comment]
BigMiterBoxes can touch the fibula a little bit with biggerMiterBoxDistanceToFibula = 0.0mm but you can change this parameter to make the bigMiterBoxes only touch the surgicalGuideBase. Also remember that to make the translation transforms of the bigMiterBoxes work well you need to have a fibulaSegment (and a fibulaModel) that has no holes inside (like the ones you get with "Threshold effect", to avoid them you can use the "Add selected island" algorythim). I think that is the problem in the picture above. 

> Can we use the fibula line to direct the Mitter boxes?

To direct the mitterBoxes you need a line, it can be created via the markups module or with the "Add fibula line" button. The line that goes from distal to proximal on the fibula (in code called "fibulaLine") and the miterBoxDirectionLine cannot be the same one.

> Hide the original mandible model when transforming fibula bone pieces to mandible is done (Keep only the "Cut mandible" visible

I think I can do that.

> 2.a change cut mandible to something more appropriate like "resected mandible"?

Ok

> Display the segments on the fibula also like on the mandible so the surgeon knows which piece goes where.

I'll try to do that

**Comment by cmfsx** [comment]
> To direct the mitterBoxes you need a line, it can be created via the markups module or with the "Add fibula line" button. The line that goes from distal to proximal on the fibula (in code called "fibulaLine") and the miterBoxDirectionLine cannot be the same one.

I meant instead of drawing a miterBoxDirectionLine is it possible to calculate the direction of the fibula line and then use the perpendicular direction of that for this purpose and assuming that we tell the fibula line to be drawn from inferior to superior or superior to inferior we can predict the Medial and lateral directions as well.  (This is just to avoid an extra step for the user) 
But i don't think it is something that needs to be worked on right now.

**Comment by mauigna06** [comment]
> I meant instead of drawing a miterBoxDirectionLine is it possible to calculate the direction of the fibula line and then use the perpendicular direction of that for this purpose and assuming that we tell the fibula line to be drawn from inferior to superior or superior to inferior we can predict the Medial and lateral directions as well. (This is just to avoid an extra step for the user)

The directions of the miterBoxes at first were calculated as the averageNormal of half of the intersection of each fibulaPlane with the fibulaModel. But this made it hard to design a surgicalGuideBase that would be compatible with the miterBoxes so I changed it to the user selecting the direction so the direction of the miter boxes (on the axial view) was constant. 
I'm not sure if it would be better to constraint the miterBoxDirectionLine to be same as -fibulaX (approximately lateral direction) because that could also make it harder to design the surgicalGuideBase.

If you didn't had any new problems regarding design of the fibulaSurgicalGuide I think we should concentrate in making GUI and functionality for the mandibleSurgicalGuides. Do you agree?

**Comment by cmfsx** [comment]
Yes we can leave mitter boxes line for now and I  agree that we can work on the GUI and the mandible surgical guide.
