### ISSUE TITLE
Orientation of the miter boxes

### ISSUE THREAD

**Issue by mrtig** [lassoan/SlicerBoneReconstructionPlanner#28]
I'm using the main branch and for some reason the first box is rotated approx 90 degrees in relation to others.
![image](https://user-images.githubusercontent.com/12380462/109267687-a224d780-7812-11eb-9529-0c078b464bd5.png)

**Comment by cmfsx** [comment]
Use the booleanOperationsExperiments branch. 
Also, you need the latest preview release with sandbox extension installed.  

The direction of the box is due to by default it takes the fibula line. Draw a separate line in the direction you want the mitter boxes to orient. (Lateral to medial) and then select that line from the drop-down list in mitter box direction line.  Then it will orient correctly. 

Also if the mitter boxes are touching the fibula, click create bone models from segmentation and click on the mitter box creation again. 

We will work on improving the GUI and the worldfow so this confusion will not happen.

**Comment by mauigna06** [comment]
Thank you Manjula for answering.

> I'm using the main branch and for some reason the first box is rotated approx 90 degrees in relation to others.

Use the booleanOperationsExperiments branch because the algorithm to select the miterBox direction that was used in main branch is deprecated. I'm going to make a few changes more to this branch and then make a pull request before continuing with experimentation so the main branch is working right.

> Also if the mitter boxes are touching the fibula,

BigMiterBoxes can touch the fibula a little bit with biggerMiterBoxDistanceToFibula = 0.0mm but you can change this parameter to make the bigMiterBoxes only touch the surgicalGuideBase. Also remember that to make the translation transforms of the bigMiterBoxes work well you need to have a fibulaSegment (and a fibulaModel) that has no holes inside (like the ones you get with "Threshold effect", to avoid them you can use the "Add selected island" algorithm). 

> click create bone models from segmentation and click on the mitter box creation

This was needed because the boneModels weren't saved in the parameter node and you had to do this when you loaded a saved-scene. But in the next commits the boneModels will save in the parameter node so this will no longer be needed.
You need to click "Create bone models from segmentations" if you have changed the fibula (or the mandible) segment and you need to update the boneModel(s).
