### ISSUE TITLE
How to get the miter boxes closer to the base

### ISSUE THREAD

**Issue by mrtig** [lassoan/SlicerBoneReconstructionPlanner#44]
How can I get the miter box closer to the base so there wouldn't be a gap between the box and the base?
The distance to fibula is set 0, but there is still a gap.
![image](https://user-images.githubusercontent.com/12380462/116085266-51f9b280-a6a7-11eb-9e57-ed86ca73b2d3.png)

**Comment by mauigna06** [comment]
The "bigger miter box distance to fibula" cannot be less that 0 because the biggerMiterBox would be intersecting the fibula and that would ruin the fibulaSurgicalGuideBase. The bone touching part of the surgical guide wouldn't be smooth and would have some irregular parts that could ruin (or at least alter) the positioning of the fibulaSurgicalGuide.

One thing that can be done is to go to the segment editor and paint over the fibulaSurgicalGuideBase to fill those gaps

Other thing that could be done but gave problems in the past didn't work is to allow negative "bigger miter box distance to fibula" and add another boolean operation to make the difference of the fibulaSurgicalGuidePrototype with the fibulaModel. 
I could set this up on a test branch and you should test it with a handful of cases. If it works well and proves to be a stable solution then it can be added to the main branch. Would you like that?

**Comment by mrtig** [comment]
Another thing I noticed is that the distance of the miter boxes varies quite a bit. it is like the bone surface variations are amplified.
![image](https://user-images.githubusercontent.com/12380462/116207915-0992d100-a749-11eb-9b7f-583a32ace5dd.png)

**Comment by mauigna06** [comment]
First thing to check here is if you Wrap-Solidified the fibula bone segment inside the segment editor before using it in BoneReconstructionPlanner. You need to do this to eliminate holes that confuse the biggerMiterBoxes positioning algorithm.
SurfaceWrapSolidify is available as a Slicer extension.
If that doesn't solve the problem upload the slicer scene corresponding to that image and I'll check it out

**Comment by lassoan** [comment]
> First thing to check here is if you Wrap-Solidified the fibula bone segment inside the segment editor before using it in BoneReconstructionPlanner

This is useful information that the users might not know and may be difficult to find if you just only show in video tutorials. Could you add a section in https://github.com/lassoan/SlicerBoneReconstructionPlanner#readme where you document such things? Thank you.

**Comment by mauigna06** [comment]
> This is useful information that the users might not know and may be difficult to find if you just only show in video tutorials. Could you add a section in https://github.com/lassoan/SlicerBoneReconstructionPlanner#readme where you document such things? Thank you.

Okey
