### ISSUE TITLE
Cut the Fibula segments/models with dynamic modeler

### ISSUE THREAD

**Issue by cmfsx** [lassoan/SlicerBoneReconstructionPlanner#9]

**Comment by mauigna06** [comment]
This is done in the last commit. Segmentations of mandible and fibula should be provided for the module to work.
Now cutted bones can be 3D printed to check if module is working right

![Screenshot](https://user-images.githubusercontent.com/19158307/103090269-5b76ef00-45cf-11eb-9ea8-a3206556116b.png)

**Comment by lassoan** [comment]
This will be awesome, now you just need to transform the bone segments to the mandible to have a preview of the final bone reconstruction.

**Comment by cmfsx** [comment]
@mauigna06 I tried it. When it does work it looks fantastic but I found it to be a bit unpredictable in instances. There seems to be a relationship between the size (dimensions) of the plane and the mirrored plane (on the fibula). So these planes intersect with each other in unpredictable ways and cut segments alone its path creating segments that are useless. 

This is how it looks when it goes wrong. 

![Screenshot from 2020-12-24 16-34-12](https://user-images.githubusercontent.com/57766971/103099107-78caae00-460d-11eb-8b21-421a276b6a6c.png)


When it cuts nicely it looks very good and ready for 3D printing with no big errors. 

![2](https://user-images.githubusercontent.com/57766971/103099135-8d0eab00-460d-11eb-8b36-998b12a3ef6f.png)

**Comment by mauigna06** [comment]
Can you share slicerScene examples that give you such errors?
Maybe the unpredictable behaviour happens because of the planes normals position. Here is an example picture of how the planes should be positioned in an axial view:
![Screenshot2](https://user-images.githubusercontent.com/19158307/103099987-59248d00-45ef-11eb-9b4b-b0f01d2fbc90.png)
The first plane is the distal one, the second one is the middle one and the third one is the mesial one. I'm not sure if this solutions the problem but let me know

**Comment by lassoan** [comment]
Currently, it is hard to place the planes correctly, but with the single-click add, the planes will be placed approximately corectly and you will just need to do slight manual adjustments.

**Comment by cmfsx** [comment]
Please find the scenes. first is after creating the planes and without been applied and the second is after applied. 

https://drive.google.com/file/d/1BvT5d0VYgnddn3qzfkrTcHblNTTe42C2/view?usp=sharing

https://drive.google.com/file/d/1ED89dtTUgfT8Dy55MMPtrF6MzvNcZfKx/view?usp=sharing

I saved the first scene before applying anything with the hops of trying out different combinations. However, when I load it and try to apply it (with modifications or without any modifications) I  get the following error. 

![Screenshot from 2020-12-25 00-30-49](https://user-images.githubusercontent.com/57766971/103111069-345d0380-4649-11eb-980b-bee254387f2c.png)

**Comment by mauigna06** [comment]
The transform formula was corrected on the last commit (so it probably won't position the fibula planes that way anymore). But there is a problem in your planning (because of how the module is made). The planes should be placed with the normal pointing to to the posterior (posterior-right) direction (aproximatelly). Please look how the normals are positioned on the example I shared you above. Also note what planes should be positioned first.

**Comment by cmfsx** [comment]
I figure out the problem with my plane placement. It is because I was not paying attention to the origin of the plane. As the transformation updates with the change of origin and this was the problem. Is it possible to make the origin of the plane constraint on to the mandibular curve so only the direction information is passed on the transform and the origin of the transformed planes on the fibul constrained on to the fibula line? This would prevent the weird cutting plane generation. And i  guess it would  solve the problem with direction as well

**Comment by mauigna06** [comment]
I'm happy that you can use the module. That means the GUI is intuitive enough.
You are right that one click plane creation would solve this kind of problems. I think it should be the next thing we work on

**Comment by lassoan** [comment]
Very nice work @mauigna06. We should talk so that I can introduce you to the approach that we developed for computing transforms for image-guided therapy applications (based on decomposing all transforms to trivially simple transforms between well-defined coordinate systems). Let me know what times would work for you on Dec 26 or later.
